from tkinter import *
window = Tk()
window.tiltle("Tkinter simple Window")
window.geometry ("300x200")
greeting = Label(window, text="Hello user" fg="black", bg="wighte")
button=Button(window, text="Click Me", bg="blue", fg="wighte")
entery=Entry(window, width=20,)
greeting.pack()
button.pack()
entry.pack()
Frame=Frame(window, width=100, height=100, bg="red")
Frame.pack()
label=Label(Frame, text="Inside Frame",fg="wight",bg="red")
label.pack()
text=Text(Window, height=5, width=30)
text.pack()
window.mainloop()